<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>ModbusLite</PackageId>
    <Version>1.0.0</Version>
    <Authors>Reza Bazdar (Godde3s)</Authors>
    <Description>Minimal Modbus TCP client for .NET — read/write coils and registers with a clean API. Built for industrial HMI tooling.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

</Project>
